site_name: FRCDesign.org
site_description: A comprehensive learning guide and technical reference for FRC design using Onshape.
site_url: https://www.FRCDesign.org

# Repository
repo_name: frcdesign/FRCDesign.org
repo_url: https://github.com/frcdesign/FRCDesign.org
edit_uri: edit/main/docs/

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.prune
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - header.autohide
  language: en

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
      primary: green
      accent: white
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
      primary: green
      accent: black
      
  icon:
    logo: fontawesome/solid/book-open
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: material/information
      tip: fontawesome/solid/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  
  favicon: img/favicon.png

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jHXTdNjYCg 
  analytics:
    provider: google
    property: G-KX3MNPJ4L6

# Page Tree
nav:
  - Home: index.md
  - Learning Course:
    - learning-course/index.md
    - Stage 0: 
      - "A: Introduction to CAD": learning-course/stage0/0A-introductionToCAD.md
      - "B: Onshape Setup": learning-course/stage0/0B-setup.md
      - "C: Navigating Onshape": learning-course/stage0/0C-navigation.md
      - "D: Theory": learning-course/stage0/0D-theory.md
    - Stage 1:
      - "A: Onshape Fundamentals": learning-course/stage1/1A-onshapeFundamentals.md
      - "B: Power Transmissions": learning-course/stage1/1B-powerTransmissions.md
      - "C: Design Methodology": learning-course/stage1/1C-designMethodology.md
    - Stage 2:
      - "A: Full Detail Drivebase": learning-course/stage2/2A-drivebaseFullDetail.md
      - "B: Basic Shooter": learning-course/stage2/2B-basicShooter.md
      - "C: Dead Axle Pivot": learning-course/stage2/2C-deadaxlePivot.md
      - "D: Slapdown Intake": learning-course/stage2/2D-slapdownIntake.md
      - "E: Cascade Elevator": learning-course/stage2/2E-cascadeElevator.md
    - Stage 3: learning-course/stage3/index.md
    - Stage 4: learning-course/stage4.md

  - Design Handbook:
    - design-handbook/index.md
    - Strategic Design: design-handbook/strategic-design.md
    - Handbook:
      - Hardware:
        - Materials: design-handbook/structure/materials.md
        - Structure: design-handbook/structure/structure.md
        - Fasteners: design-handbook/structure/fasteners.md
        - Sheet Metal: design-handbook/structure/sheet-metal.md
        - 3D Printing: design-handbook/structure/3d-printing.md
        - Tolerances: design-handbook/structure/tolerances.md
        - Weight Saving: design-handbook/structure/weight-savings.md
      - Power Transmission:
        - Motion Components: design-handbook/power-transmission/motion-components.md
        - Transfer of Rotational Motion: design-handbook/power-transmission/rotation.md
        - Linear Extension: design-handbook/power-transmission/linear-extension.md
        - Motors: design-handbook/power-transmission/motors.md
        - Wheels and Rollers: design-handbook/power-transmission/wheels-rollers.md
        - Pneumatics: design-handbook/power-transmission/pneumatics.md
        - Electronics and Sensors: design-handbook/power-transmission/electronics-sensors.md
      - Mechanisms:
        - Drivetrains: design-handbook/mechanisms/drivetrains.md
        - Elevators: design-handbook/mechanisms/elevators.md
        - Arms: design-handbook/mechanisms/arms.md
        - Linkages: design-handbook/mechanisms/linkages.md
        - Intakes: design-handbook/mechanisms/intakes.md
        - Shooters: design-handbook/mechanisms/shooters.md
        - Turrets: design-handbook/mechanisms/turrets.md
        - Bumpers: design-handbook/mechanisms/bumpers.md
      - Design Write-ups:
        - Designing for Controllability: design-handbook/design-writeups/DFC.md
        - Chain Tensioning Solutions: design-handbook/design-writeups/chainTensioning.md
        - Bumper Mounting Solutions: design-handbook/design-writeups/bumperMounting.md
        - Springs and Shocks: design-handbook/design-writeups/springs-shocks.md

  - Mechanism Examples:
      - mechanism-examples/index.md
      - Drivebases:
        - mechanism-examples/drivebase/index.md
        - 2910's Charged Up Drivebase: mechanism-examples/drivebase/2910.md
        - 972's Brainpan Drivebase: mechanism-examples/drivebase/brainpan.md
      - Shooters:
        - mechanism-examples/shooter/index.md
        - Andrew's Hyperhive Shooter: mechanism-examples/shooter/small.md
        - 1678's Rapid React Shooter: mechanism-examples/shooter/citrus.md
      - Slapdown Intakes:
        - mechanism-examples/intake/slapdown/index.md
        - 4414-Style Intake: mechanism-examples/intake/slapdown/4414style.md
        - Washed Beavertail Intake: mechanism-examples/intake/slapdown/washed.md
        - Low Pivot Slapdown Intake: mechanism-examples/intake/slapdown/low.md
        - 6423's Crescendo Slapdown Intake: mechanism-examples/intake/slapdown/6423otb.md
      - 4 Bar Intakes:
        - mechanism-examples/intake/4bar/index.md
        - 1678's Rapid React Intake: mechanism-examples/intake/4bar/1678.md
        - Andrew's Four-Bar Intake: mechanism-examples/intake/4bar/clean.md
        - Vaughn's Four-Bar Intake: mechanism-examples/intake/4bar/vaughn4bar.md
      - Continuous Elevators:
        - mechanism-examples/elevator/continuous/index.md
        - External Cable Driven Elevator: mechanism-examples/elevator/continuous/cable.md
        - Internal Belt Driven Elevator: mechanism-examples/elevator/continuous/belt.md
      - Cascade Elevators:
        - mechanism-examples/elevator/cascade/index.md
        - 2 Stage Cascade Elevator: mechanism-examples/elevator/cascade/2stage.md
        - 3 Stage Cascade Elevator: mechanism-examples/elevator/cascade/3stage.md
      - Pivots:
        - mechanism-examples/pivots/index.md
        - 6328 A-Frame Pivot: mechanism-examples/pivots/6328pivot.md
        - 2910 Dead Axle Pivot: mechanism-examples/pivots/2910pivot.md

  - Best Practices:
      - best-practices/index.md
      - Document Setup: best-practices/document-setup.md
      - Sub-Document Setup: best-practices/sub-document-setup.md
      - Master Sketch Best Practices: best-practices/mastersketch-setup.md
      - Part Studio Best Practices: best-practices/feature-tree-setup.md
      - Assembly Best Practices: best-practices/assembly-setup.md
    
  - Design Challenges:
    - design-challenge/index.md
    - Week 1 | Swerve Drivebase: design-challenge/challenges/week1.md
    - Week 2 | Gearboxes: design-challenge/challenges/week2.md
    - Week 3 | Ball Shooter: design-challenge/challenges/week3.md
    - Week 4 | Intake: design-challenge/challenges/week4.md
    - Week 5 | Tilt Shift: design-challenge/challenges/week5.md

  - Other Resources:
    - resources/index.md
    - Glossary: resources/glossary.md

    - CAD Resources:
      - Featurescripts : resources/featurescripts.md
      - Simplified Models: resources/simplified.md
      - Configurables: resources/configurables.md
      - KrayonCAD: resources/krayonCAD.md
    

  - Contribution Guide:
    - Methods of Contributing: contribution/methodsOfContributing.md
    - Contributing to Mech. Examples: contribution/mechanismContribution.md
    - Style Guide: contribution/styleguide.md
    - Contributors: contribution/contributors.md
  

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css: [stylesheets/extra.css]

watch:
  - includes

plugins:
  - glightbox:
      background: none
      width: 90%
      shadow: true
  - search
    
  - group: # These plugins only run when the site is deployed
      enabled: !ENV CI
      plugins:
      - git-committers:
          repository: frcdesign/FRCDesign.org
          branch: main
      - git-revision-date-localized:
          enable_creation_date: true
      - optimize
    
  - group: 
      enabled: !ENV INSIDERS
      plugins:
        - meta
        - social:
            cards_layout_dir: layouts
            cards_layout: default_page
            cards_layout_options:
                font_family: Roboto
            debug: false