site_name: FRCDesign.org
site_description: A comprehensive learning guide and technical reference for FRC design using Onshape.
site_url: https://www.FRCDesign.org

# Repository
repo_name: frcdesign/FRCDesign.org
repo_url: https://github.com/frcdesign/FRCDesign.org
edit_uri: edit/main/docs/

copyright: Need custom laser cut parts for your robot? Check out our sponsor <a href="https://go.fabworks.com/frcdesign" class="footerlink"/>Fabworks.</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.footer
    - navigation.prune
    - navigation.top
    - navigation.path
    - toc.follow
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - content.action.edit
    - content.action.view
    - header.autohide
  language: en

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to Light Mode
      primary: green
      accent: white
    
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to Dark Mode
      primary: green
      accent: black
      
  icon:
    logo: fontawesome/solid/book-open
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: material/information
      tip: fontawesome/solid/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  
  favicon: img/favicon.png

# Additional Configuration
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jHXTdNjYCg 
  analytics:
    provider: google
    property: G-KX3MNPJ4L6

# Page Tree
nav:
  - Home: index.md
  - Website Feature Guide: website-feature-guide.md
  - Learning Course:
    - learning-course/index.md
    - Stage 0: 
      - "A: Introduction to CAD":
        - "What and Why": learning-course/stage0/0A/what-and-why-CAD.md
        - "CAD Software": learning-course/stage0/0A/cad-software.md

      - "B: Onshape Setup":
        - "Account Setup": learning-course/stage0/0B/account-setup.md
        - "MKCad": learning-course/stage0/0B/MKCad.md
        - "Featurescripts": learning-course/stage0/0B/featurescripts.md

      - "C: Navigating Onshape":
        - "Documents Page": learning-course/stage0/0C/documents.md
        - "Document Navigation": learning-course/stage0/0C/document-navigation.md
        - "Other Notes": learning-course/stage0/0C/other-notes.md
      - "D: CAD Theory": learning-course/stage0/0D/theory.md
      - "Summary": learning-course/stage0/summary.md

    - Stage 1:
      - "A: Onshape Fundamentals":
        - "Introduction": learning-course/stage1/1A/introduction.md
        - "Sketching and Part Modeling": learning-course/stage1/1A/sketch-part-modeling.md
        - "Exercise Prequisites": learning-course/stage1/1A/exercise-setup.md
        - "Exercise 1: Simple Box Tube": learning-course/stage1/1A/exercise1.md
        - "Multi-Body Modeling": learning-course/stage1/1A/multi-body.md
        - "Exercise 2: Gusset Joint": learning-course/stage1/1A/exercise2.md
        - "Assembly Modeling": learning-course/stage1/1A/assembly.md
        - "Exercise 3: Box Tube Frame": learning-course/stage1/1A/exercise3.md
        - "Exercise 4: Climber Hook": learning-course/stage1/1A/exercise4.md
        - "Summary": learning-course/stage1/1A/summary.md

      - "B: Power Transmissions":
        - "Introduction": learning-course/stage1/1B/introduction.md
        - "Motors": learning-course/stage1/1B/motors.md
        - "Shafts and Bearings": learning-course/stage1/1B/shafts-bearings.md
        - "Torque and Speed": learning-course/stage1/1B/torque-speed.md
        - "Gear Basics": learning-course/stage1/1B/gears.md
        - "Exercise 1: Simple Gearbox": learning-course/stage1/1B/exercise1.md
        - "Exercise 2: Two Stage Gearbox": learning-course/stage1/1B/exercise2.md
        - "Belt and Pulley Basics": learning-course/stage1/1B/belts.md
        - "Chain and Sprocket Basics": learning-course/stage1/1B/chain.md
        - "Exercise 3: Gear and Belt Gearbox": learning-course/stage1/1B/exercise3.md
        - "Summary": learning-course/stage1/1B/summary.md

      - "C: Practice Mechanisms": 
        - "Introduction": learning-course/stage1/1C/introduction.md
        - "Exercise Overview": learning-course/stage1/1C/exercise-overview.md
        - "Exercise 1: Flat Intake": learning-course/stage1/1C/exercise1.md
        - "Exercise 2: Dead Axle Rollers": learning-course/stage1/1C/exercise2.md
        - "Exercise 3: Shooter": learning-course/stage1/1C/exercise3.md
        - "Exercise 4: Telescoping Hook": learning-course/stage1/1C/exercise4.md
        - "Exercise 5: Flipped Gearbox": learning-course/stage1/1C/exercise5.md
        - "Exercise 6: Direction Swap": learning-course/stage1/1C/exercise6.md
        - "Exercise 7: Vertical Rollers": learning-course/stage1/1C/exercise7.md
        - "Exercise 8: Indexer Centering": learning-course/stage1/1C/exercise8.md
        - "Summary": learning-course/stage1/1C/summary.md

      - "D: Design Methodology":
        - "Introduction": learning-course/stage1/1D/introduction.md
        - "Top Down Design": learning-course/stage1/1D/top-down-design.md
        - "Project Overview": learning-course/stage1/1D/project-overview.md
        - "Layout Sketch": learning-course/stage1/1D/layout-sketch.md
        - "Part Studio": learning-course/stage1/1D/part-modeling.md
        - "Assembly": learning-course/stage1/1D/assembly-modeling.md
        - "Adding More Components": learning-course/stage1/1D/adding-components.md
        - "Top Level Assembly": learning-course/stage1/1D/top-level-assembly.md
        - "Summary": learning-course/stage1/1D/summary.md

      - "E: Subsystem Workflow":
        - "Introduction": learning-course/stage1/1E/introduction.md
        - "Project Overview": learning-course/stage1/1E/project-overview.md
        - "Battery Mounting": learning-course/stage1/1E/battery-mounting.md
        - "Exercise: Battery Holder": learning-course/stage1/1E/exercise1.md
        - "Electronics": learning-course/stage1/1E/electronics.md
        - "Exercise: Mounting Electronics": learning-course/stage1/1E/exercise2.md
        - "Exercise: Bellypan Pocketing": learning-course/stage1/1E/exercise3.md
        - "Exercise: Bumpers": learning-course/stage1/1E/exercise4.md
        - "Exercise: Bumper Mounting": learning-course/stage1/1E/exercise5.md
        - "Summary": learning-course/stage1/1E/summary.md
      
    - Stage 2:

      - "A: Basic Shooter":
        - "Introduction": learning-course/stage2/2A/introduction.md
        - "Project Overview": learning-course/stage2/2A/project-overview.md
        - "Engineering Concepts":
          - "Structure Rigidity": learning-course/stage2/2A/structure-rigidity.md
          - "Ball Trajectory": learning-course/stage2/2A/ball-trajectory.md
          - "Exit Velocity": learning-course/stage2/2A/exit-velocity.md
          - "Compression & Wrap": learning-course/stage2/2A/compression-wrap.md
          - "Spin Control": learning-course/stage2/2A/spin-control.md
          - "Friction & Efficiency": learning-course/stage2/2A/friction-efficiency.md
        - "Layout Sketch": learning-course/stage2/2A/layout-sketch.md
        - "Part Studio": learning-course/stage2/2A/part-studio.md
        - "Assembly": learning-course/stage2/2A/assembly.md
        - "Summary": learning-course/stage2/2A/summary.md

      - "B: Dead Axle Pivot":
        - "Introduction": learning-course/stage2/2B/introduction.md
        - "Project Overview": learning-course/stage2/2B/project-overview.md
        - "Engineering Concepts":
          - "Strength": learning-course/stage2/2B/strength.md
          - "Friction": learning-course/stage2/2B/friction.md
          - "Power Transmission": learning-course/stage2/2B/power-transmission.md
          - "Tensioning": learning-course/stage2/2B/tensioning.md
          - "Backlash": learning-course/stage2/2B/backlash.md
        - "Layout Sketch": learning-course/stage2/2B/layout-sketch.md
        - "Part Studio": learning-course/stage2/2B/part-studio.md
        - "Assembly": learning-course/stage2/2B/assembly.md
        - "Summary": learning-course/stage2/2B/summary.md

      - "C: Slapdown Intake":
        - "Introduction": learning-course/stage2/2C/introduction.md
        - "Project Overview": learning-course/stage2/2C/project-overview.md
        - "Engineering Concepts":
          - "Intake Golden Rules": learning-course/stage2/2C/intake-golden-rules.md
          - "Robustness": learning-course/stage2/2C/robustness.md
          - "Pivot": learning-course/stage2/2C/pivot.md
          - "Rollers": learning-course/stage2/2C/rollers.md
          - "Zombie Axles": learning-course/stage2/2C/zombie-axles.md
        - "Layout Sketch": learning-course/stage2/2C/layout-sketch.md
        - "Part Studio": learning-course/stage2/2C/part-studio.md
        - "Assembly": learning-course/stage2/2C/assembly.md
        - "Summary": learning-course/stage2/2C/summary.md

      - "D: Cascade Elevator":
        - "Introduction": learning-course/stage2/2D/introduction.md
        - "Project Overview": learning-course/stage2/2D/project-overview.md
        - "Engineering Concepts":
          - "Elevator Blocks": learning-course/stage2/2D/elevator-blocks.md
          - "Chain Attachment": learning-course/stage2/2D/chain-attachment.md
          - "Rigging": learning-course/stage2/2D/rigging.md
          - "Cable Clamp": learning-course/stage2/2D/cable-clamp.md
          - "Cable Ends": learning-course/stage2/2D/cable-ends.md
          - "Gearbox": learning-course/stage2/2D/drive-system.md
        - "Layout Sketch": learning-course/stage2/2D/layout-sketch.md
        - "Part Studio": learning-course/stage2/2D/part-studio.md
        - "Assembly": learning-course/stage2/2D/assembly.md
        - "Summary": learning-course/stage2/2D/summary.md

    - Stage 3: learning-course/stage3/3A/introduction.md
    - Stage 4: learning-course/stage4.md

  - Design Handbook:
    - design-handbook/index.md
    - Strategic Design: design-handbook/strategic-design.md
    - Handbook:
      - Hardware:
        - Materials: design-handbook/structure/materials.md
        - Structure: design-handbook/structure/structure.md
        - Fasteners: design-handbook/structure/fasteners.md
        - Sheet Metal: design-handbook/structure/sheet-metal.md
        - 3D Printing: design-handbook/structure/3d-printing.md
        - Tolerances: design-handbook/structure/tolerances.md
        - Weight Saving: design-handbook/structure/weight-savings.md
      - Power Transmission:
        - Motion Components: design-handbook/power-transmission/motion-components.md
        - Transfer of Rotational Motion: design-handbook/power-transmission/rotation.md
        - Linear Extension: design-handbook/power-transmission/linear-extension.md
        - Motors: design-handbook/power-transmission/motors.md
        - Wheels and Rollers: design-handbook/power-transmission/wheels-rollers.md
        - Pneumatics: design-handbook/power-transmission/pneumatics.md
        - Electronics and Sensors: design-handbook/power-transmission/electronics-sensors.md
      - Mechanisms:
        - Drivetrains: design-handbook/mechanisms/drivetrains.md
        - Elevators: design-handbook/mechanisms/elevators.md
        - Arms: design-handbook/mechanisms/arms.md
        - Linkages: design-handbook/mechanisms/linkages.md
        - Intakes: design-handbook/mechanisms/intakes.md
        - Shooters: design-handbook/mechanisms/shooters.md
        - Turrets: design-handbook/mechanisms/turrets.md
        - Bumpers: design-handbook/mechanisms/bumpers.md
      - Design Write-ups:
        - Designing for Controllability: design-handbook/design-writeups/DFC.md
        - Chain Tensioning Solutions: design-handbook/design-writeups/chainTensioning.md
        - Bumper Mounting Solutions: design-handbook/design-writeups/bumperMounting.md
        - Springs and Shocks: design-handbook/design-writeups/springs-shocks.md

  - Mechanism Examples:
      - mechanism-examples/index.md
      - Drivebases:
        - mechanism-examples/drivebase/index.md
        - 2910's Charged Up Drivebase: mechanism-examples/drivebase/2910.md
        - 972's Brainpan Drivebase: mechanism-examples/drivebase/brainpan.md
      - Shooters:
        - mechanism-examples/shooter/index.md
        - Andrew's Hyperhive Shooter: mechanism-examples/shooter/small.md
        - 1678's Rapid React Shooter: mechanism-examples/shooter/citrus.md
      - Slapdown Intakes:
        - mechanism-examples/intake/slapdown/index.md
        - 4414-Style Intake: mechanism-examples/intake/slapdown/4414style.md
        - Washed Beavertail Intake: mechanism-examples/intake/slapdown/washed.md
        - Low Pivot Slapdown Intake: mechanism-examples/intake/slapdown/low.md
        - 6423's Crescendo Slapdown Intake: mechanism-examples/intake/slapdown/6423otb.md
      - 4 Bar Intakes:
        - mechanism-examples/intake/4bar/index.md
        - 1678's Rapid React Intake: mechanism-examples/intake/4bar/1678.md
        - Andrew's Four-Bar Intake: mechanism-examples/intake/4bar/clean.md
        - Vaughn's Four-Bar Intake: mechanism-examples/intake/4bar/vaughn4bar.md
      - Continuous Elevators:
        - mechanism-examples/elevator/continuous/index.md
        - External Cable Driven Elevator: mechanism-examples/elevator/continuous/cable.md
        - Internal Belt Driven Elevator: mechanism-examples/elevator/continuous/belt.md
      - Cascade Elevators:
        - mechanism-examples/elevator/cascade/index.md
        - 2 Stage Cascade Elevator: mechanism-examples/elevator/cascade/2stage.md
        - 3 Stage Cascade Elevator: mechanism-examples/elevator/cascade/3stage.md
      - Pivots:
        - mechanism-examples/pivots/index.md
        - 6328 A-Frame Pivot: mechanism-examples/pivots/6328pivot.md
        - 2910 Dead Axle Pivot: mechanism-examples/pivots/2910pivot.md

  - CAD Best Practices:
      - best-practices/index.md
      - Document Setup: best-practices/document-setup.md
      - Sub-Document Setup: best-practices/sub-document-setup.md
      - Master Sketch Best Practices: best-practices/mastersketch-setup.md
      - Part Studio Best Practices: best-practices/feature-tree-setup.md
      - Assembly Best Practices: best-practices/assembly-setup.md
    
  - Design Challenges:
    - design-challenge/index.md
    - Week 1 | Swerve Drivebase: design-challenge/challenges/week1.md
    - Week 2 | Gearboxes: design-challenge/challenges/week2.md
    - Week 3 | Ball Shooter: design-challenge/challenges/week3.md
    - Week 4 | Intake: design-challenge/challenges/week4.md
    - Week 5 | Tilt Shift: design-challenge/challenges/week5.md

  - Other Resources:
    - resources/index.md
    - Glossary: resources/glossary.md

    - CAD Resources:
      - Featurescripts : resources/featurescripts.md
      - Simplified Models: resources/simplified.md
      - Configurables: resources/configurables.md
      - KrayonCAD: resources/krayonCAD.md
    

  - Contribution:
    - Methods of Contributing: contribution/methodsOfContributing.md
    - Contributing to Mech. Examples: contribution/mechanismContribution.md
    - Style Guide: contribution/styleguide.md
    - Contributors: contribution/contributors.md
  

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css: [stylesheets/extra.css]

watch:
  - includes

plugins:
  - glightbox:
      background: none
      width: 90%
      shadow: true
  - search
  # - meta
    
  - group: # These plugins only run when the site is deployed
      enabled: !ENV CI
      plugins:
      - git-revision-date-localized:
          enable_creation_date: true
      - optimize
    
  - group: 
      enabled: !ENV INSIDERS
      plugins:
        - meta
        - social:
            cards_layout_dir: layouts
            cards_layout: default_page
            debug: false


extra_javascript:
  - javascripts/extra.js
