site_name: DDS Manual
theme:
  name: material
  features:
    - navigation.sections
    - toc.integrate
    - navigation.top
    - navigation.indexes
    - navigation.path
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to Light Mode
      primary: green
      accent: white
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to Dark Mode
      primary: green
      accent: white
    

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jHXTdNjYCg 

nav:
  - Home: index.md
  - Beginner Guide:
    - Onshape Intro: onshape-intro.md
    - Starter Projects: starter-projects.md
  - Resources:
    - Glossary:
      - glossary/index.md
    - CAD Examples:
      - cad-examples/index.md
      - Slapdown Intakes:
        - cad-examples/intake/slapdown/index.md
        - 4414 Style  Intake: cad-examples/intake/slapdown/examples/4414style.md
        - Washed Beavertail Intake: cad-examples/intake/slapdown/examples/washed.md
        - Low Pivot Slapdown Intake: cad-examples/intake/slapdown/examples/low.md
      - 4 Bar Intakes:
        - cad-examples/intake/4bar/index.md
        - 1678's 2022 Intake: cad-examples/intake/4bar/examples/1678.md
        - Andrew's Clean 4 Bar Intake: cad-examples/intake/4bar/examples/clean.md
      - Cascade Elevators:
        - cad-examples/elevator/cascade/index.md
        - 2 Stage Cascade Elevator: cad-examples/elevator/cascade/examples/2stage.md
        - 3 Stage Cascade Elevator: cad-examples/elevator/cascade/examples/3stage.md
      - Continuous Elevators:
        - cad-examples/elevator/continuous/index.md
        - External Cable Driven Elevator: cad-examples/elevator/continuous/examples/cable.md
        - Internal Belt Driven Elevator: cad-examples/elevator/continuous/examples/belt.md
      - Shooters:
        - cad-examples/shooter/index.md
        - Andrew's Hyperhive Shooter: cad-examples/shooter/examples/small.md


markdown_extensions:
  - attr_list
  - def_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra_css: [stylesheets/extra.css]
